import { nav } from "@/configs"

import { Footer } from "@/components/Footer"
import { Header } from "@/components/Header"
import { Layout } from "@/components/Layout"
import "@/styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-200">
        <Header items={nav} />
        <Layout>{children}</Layout>
        <Footer items={nav} />
      </body>
    </html>
  )
}
